#!/bin/sh
#
# $Id$
#
# PROVIDE: microca
# REQUIRE: LOGIN

. /etc/rc.subr

name="microca";

rcvar="microca_enable"

pidfile="/var/run/microca/microca.pid"
#procname="/usr/local/sbin/${name}"
command="/usr/local/sbin/${name}"
command_args=""

load_rc_config ${name}

: ${microca_enable:="NO"}

run_rc_command "$1"
#EOF
